---

- name: Install ansible prereqs
  apt:
    name: "{{ item }}"
  loop:
    - gnupg
    - python3-apt

- name: Add ansible debian repo
  apt_repository:
    repo: ppa:ansible/ansible
    codename: bionic
    update_cache: yes

- name: Install ansible
  apt:
    name: ansible

#- name: Install pyyaml python module
#  pip:
#    name: pyyaml
#    executable: pip3

- name: Copy add_new_nodes.py script
  copy:
    src: node_provisioning/add_new_nodes.py
    dest: "{{ homek8s_gateway_base_dir }}/scripts/add_new_nodes.py"
    mode: 'u=rwx,g=rx,o='
    owner: root
    group: root

# ToDo: for the next two tasks we should use synchronize (rsync) instead of copy
# Problem: currently (ansible 2.9 with python 2 from PPA) this crashes with
# broken pipe error, see https://github.com/ansible/ansible/issues/56629
# The fix would be to use ansible with python 3 but the PPA packages
# only package python 2, see https://github.com/ansible/ansible/issues/57342
# When the ansible PPA package updates to python3 we change copy to synchronize

- name: Copy k3s provisioning ansible playbooks
  copy:
    src: node_provisioning/playbooks
    dest: "{{ homek8s_gateway_base_dir }}/"
    owner: root
    group: root
    mode: u=rwX,g=rX,o=

# copy all homek8s roles from the homek8s container image to the gateway
# (because we have some roles needed in the homek8s container image
# as well as on the gateway to provision new nodes, e.g. role os_base)
- name: Copy homek8s ansible roles
  copy:
    src: /etc/ansible/roles
    dest: "{{ homek8s_gateway_base_dir }}/playbooks/"
    owner: root
    group: root
    mode: u=rwX,g=rX,o=

- name: Copy initial ansible inventory file for nodes
  template:
    src: node_provisioning/hosts.yml.j2
    dest: "{{ homek8s_gateway_base_dir }}/hosts.yml"
    owner: root
    group: root
    mode: u=rw,g=,o=
    force: no

- name: Copy ssh key pair to give gateway access to nodes
  copy:
    src: "{{ item }}"
    dest: "{{ homek8s_gateway_base_dir }}/"
    owner: "root"
    mode: 'u=rw,g=,o='
  loop:
    - "/homek8s/id_rsa"
    - "/homek8s/id_rsa.pub"

- name: Copy homek8s systemd timer and service units for new-node provisioning
  template:
    src: "{{ item.src }}"
    dest: /etc/systemd/system/{{ item.dest_filename }}
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  loop:
    - { src: "node_provisioning/homek8s-provisioner.timer.j2", dest_filename: "homek8s-provisioner.timer" }
    - { src: "node_provisioning/homek8s-provisioner.service.j2", dest_filename: "homek8s-provisioner.service" }

- name: Enable and start the homek8s-provisioner timer unit
  systemd:
    name: homek8s-provisioner.timer
    state: started
    enabled: yes
    daemon_reload: yes