---
  - name: restart dhcpcd
    systemd:
      name: dhcpcd
      state: restarted
      enabled: yes
      daemon_reload: yes

  - name: restart dnsmasq
    systemd:
      name: dnsmasq
      state: restarted
      enabled: yes
      daemon_reload: yes

  - name: save iptables
    shell:
      cmd: iptables-save > /etc/iptables.ipv4.nat